[build]
  base = "frontend"
  publish = "build"
  command = "npm install && npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  VITE_API_URL = "https://peecer-a07aa1749040.herokuapp.com/"