GET ${apiUrl}/users

###

POST ${apiUrl}/users
Content-Type: application/json

{
    "name": "Alex Inglis",
    "email": "alexinglis7799@gmail.com",
    "password": "fidelis99"
} 

###

POST ${apiUrl}/login
Content-Type: application/json

{
    "email": "alexinglis7799@gmail.com",
    "password": "Fidelis99"
}
###

GET ${apiUrl}/users/65e7658b225fac15d63b08fe

###
GET ${apiUrl}/posts/rootposts

###
GET ${apiUrl}/posts/65f4848bc58b6f6cd858f841/children