GET ${process.env.REACT_APP_API_URL}/users

###

POST ${process.env.REACT_APP_API_URL}/users
Content-Type: application/json

{
    "name": "Alex Inglis",
    "email": "alexinglis7799@gmail.com",
    "password": "fidelis99"
} 

###

POST ${process.env.REACT_APP_API_URL}/login
Content-Type: application/json

{
    "email": "alexinglis7799@gmail.com",
    "password": "Fidelis99"
}
###

GET ${process.env.REACT_APP_API_URL}/users/65e7658b225fac15d63b08fe

###
GET ${process.env.REACT_APP_API_URL}/posts/rootposts

###
GET ${process.env.REACT_APP_API_URL}/posts/65f4848bc58b6f6cd858f841/children