GET http://localhost:4578/users

###

POST http://localhost:4578/users
Content-Type: application/json

{
    "name": "Alex Inglis",
    "email": "alexinglis7799@gmail.com",
    "password": "fidelis99"
}

###

POST http://localhost:4578/login
Content-Type: application/json

{
    "email": "alexinglis7799@gmail.com",
    "password": "Fidelis99"
}
###

GET http://localhost:4578/users/65e7658b225fac15d63b08fe